#!/bin/sh

##
## Usage: list-vpn-clients [-revoked]
##

if [ "$1" = '-revoked' ]; then
    awk -F "CN=" '/^R/{if(NR>1){print $2}}' /etc/openvpn/easy-rsa/pki/index.txt
else
    awk -F "CN=" '/^V/{if(NR>1){print $2}}' /etc/openvpn/easy-rsa/pki/index.txt
fi