#!/bin/sh

client=${1?"You must specify a client name"}

FOUND=0
for c in $(pki-list-clients); do
    if [ "$c" = "$client" ]; then
        FOUND=1
        break
    fi
done

if [ $FOUND -eq 0 ]; then
    echo "Client $client does not exist" >&2
    exit 1
fi

echo "Revoking client ${client}"
cd /usr/share/easy-rsa/
./easyrsa --batch --pki-dir=/etc/openvpn/easy-rsa/pki revoke $client
./easyrsa --batch --pki-dir=/etc/openvpn/easy-rsa/pki gen-crl